name: BuildLLVMCMake

on:
  push:
    branches: [ "test-build-llvm" ]

  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      runs-on:
        description: "Runner to use for the build"
        required: true
        type: choice
        options:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-13 # x86_64
          - macos-14 # arm64

jobs:
  prepare:
    name: Prepare to build binaries
    runs-on: ${{ inputs.runs-on }}
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
      ref: ${{ steps.vars.outputs.ref }}
      #upload: ${{ steps.vars.outputs.upload }}
      target-cmake-flags: ${{ steps.vars.outputs.target-cmake-flags }}
      #build-flang: ${{ steps.vars.outputs.build-flang }}
      #enable-pgo: ${{ steps.vars.outputs.enable-pgo }}
      release-binary-basename: ${{ steps.vars.outputs.release-binary-basename }}
      release-binary-filename: ${{ steps.vars.outputs.release-binary-filename }}

    steps:
    # It's good practice to use setup-python, but this is also required on macos-14
    # due to https://github.com/actions/runner-images/issues/10385
    - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
      with:
        python-version: '3.12'

    - name: Checkout builder repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # for print_os_arch.py

    - name: Inspect cwd
      shell: bash
      run: ls -lh

    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: 'llvm/llvm-project'
        ref: 'llvmorg-${{ inputs.release-version }}'
        path: 'llvmproj'
        clean: false
        fetch-depth: 1

    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r ./llvmproj/llvm/utils/git/requirements.txt

    - name: Inspect cwd again
      shell: bash
      run: ls -lh

    - name: Collect Variables
      id: vars
      shell: bash
      run: |
        trimmed=$(echo ${{ inputs.release-version }} | xargs)
        release_version="$trimmed"
        ref="llvmorg-$release_version"
        upload="false"

        echo "release-version=$release_version">> $GITHUB_OUTPUT
        echo "ref=$ref" >> $GITHUB_OUTPUT
        echo "upload=$upload" >> $GITHUB_OUTPUT

        # Detect necessary CMake flags
        target=$(python3 print_os_arch.py)

        release_binary_basename="LLVM-$release_version-$target"
        echo "release-binary-basename=$release_binary_basename" >> $GITHUB_OUTPUT
        echo "release-binary-filename=$release_binary_basename.tar.xz" >> $GITHUB_OUTPUT

        echo "enable-pgo=false" >> $GITHUB_OUTPUT
        target_cmake_flags="-DLLVM_RELEASE_ENABLE_PGO=OFF"
        # The macOS builds try to cross compile some libraries so we need to
        # add extra CMake args to disable them.
        # See https://github.com/llvm/llvm-project/issues/99767
        if [ "${{ runner.os }}" = "macOS" ]; then
          target_cmake_flags="$target_cmake_flags -DCOMPILER_RT_ENABLE_IOS=OFF"
          if [ "${{ runner.arch }}" = "ARM64" ]; then
            arches=arm64
          else
            arches=x86_64
          fi
          target_cmake_flags="$target_cmake_flags -DDARWIN_osx_ARCHS=$arches -DDARWIN_osx_BUILTIN_ARCHS=$arches"
        fi

        build_flang="false"

        if [ "${{ runner.os }}" = "Windows" ]; then
          # The build times out on Windows, so we need to disable LTO.
          target_cmake_flags="$target_cmake_flags -DLLVM_RELEASE_ENABLE_LTO=OFF"
        fi

        echo "target-cmake-flags=$target_cmake_flags" >> $GITHUB_OUTPUT
        echo "build-flang=$build_flang" >> $GITHUB_OUTPUT

        
  build-llvm-clang:
    name: "Build LLVM and Clang"
    needs: prepare
    runs-on: ${{ inputs.runs-on }}
    steps:

    - name: Install Ninja
      uses: llvm/actions/install-ninja@22e9f909d35b50bd1181709564bfe816eaeaae81 # main

    - name: Checkout builder repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # for BuildClangTenjinRelease.cmake

    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: 'llvm/llvm-project'
        ref: ${{ needs.prepare.outputs.ref }}
        path: 'llvmproj'
        clean: false
        fetch-depth: 1

    - name: Print ldd/glibc version
      shell: bash
      run: |
        ldd --version

    - name: Configure Clang
      shell: bash
      run: |
        #sed -i.bak 's/check_library_exists(atomic __atomic_fetch_add_8 "" LIBCXX_HAS_ATOMIC_LIB)//' llvmproj/libcxx/cmake/config-ix.cmake && rm llvmproj/libcxx/cmake/config-ix.cmake.bak

        mkdir libcxx
        # There were some issues on the ARM64 MacOS runners with trying to build x86 object,
        # so we need to set some extra cmake flags to disable this.
        cmake -G Ninja -S llvmproj/llvm -B llvmproj/_build \
            ${{ needs.prepare.outputs.target-cmake-flags }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DLLVM_PARALLEL_LINK_JOBS=1 \
            -C BuildClangTenjinRelease.cmake \
            -DBOOTSTRAP_CPACK_PACKAGE_FILE_NAME="${{ needs.prepare.outputs.release-binary-basename }}" \
            -DBOOTSTRAP_CMAKE_INSTALL_PREFIX=$PWD/libcxx \
            -DBOOTSTRAP_COMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF \
            -DBOOTSTRAP_CMAKE_SYSROOT=$PWD/llvmproj/_build/clickhouse-sysroot \
            -DBOOTSTRAP_LLVM_PARALLEL_LINK_JOBS=1
            #-DLLVM_ENABLE_CURL=OFF \
            #-DLLVM_ENABLE_HTTPLIB=OFF \

        # We build clang with a relative path for default sysroot (in stage 2),
        # and so must provide a suitable sysroot for the runtimes compilation,
        # which occurs during the stage2-package step.
        wget https://images.aarno-labs.com/amp/ben/sysroots/clickhouse-sysroot-x86_64-linux.tar.xz
        tar xf clickhouse-sysroot-x86_64-linux.tar.xz
        cp -r clickhouse-sysroot llvmproj/_build/

        ls -l libcxx
            
    - name: Build Clang (only)
      shell: bash
      run: |
        ninja -v -C llvmproj/_build stage2-clang

        # I'm not sure where it needs to go to get picked up for the next part so let's put it in both...
        release_dir=`find llvmproj/_build -iname stage2-bins`
        cp -r clickhouse-sysroot $release_dir


    - name: Build Clang (package)
      shell: bash
      run: |
        ninja -v -C llvmproj/_build stage2-package

    - name: Install libcxx
      shell: bash
      run: |

        ls -l libcxx
        ninja -v -C llvmproj/_build stage2-install-runtimes
        ls -l libcxx

    - name: Prep Package
      shell: bash
      run: |
        # Copy Release artifact to the workspace so it is easier to upload.
        # This is necessary, because on Windows, the build-prefix path can
        # only be used on bash steps, because it uses the form of /d/files/
        # and other steps expect D:\files.
        find llvmproj/_build -iname ${{ needs.prepare.outputs.release-binary-filename }}
        release_dir=`find llvmproj/_build -iname stage2-bins`
        mv $release_dir/${{ needs.prepare.outputs.release-binary-filename }} .
        ls ${{ needs.prepare.outputs.release-binary-filename }}
        ls -l libcxx

        # The .a files that feed in to libLLVM and libClang are huge and we don't need them!
        # But CMake will barf if they are missing, so we'll replace them with empty files.
        mkdir dota
        tar xf ${{ needs.prepare.outputs.release-binary-filename }}
        ls -lh ${{ needs.prepare.outputs.release-binary-filename }}
        rm     ${{ needs.prepare.outputs.release-binary-filename }}
        for x in `ls ${{ needs.prepare.outputs.release-binary-basename }}/lib/*.a`; do
          mv $x dota/
          touch $x
        done
        echo '-fuse-ld=lld --rtlib=compiler-rt' > ${{ needs.prepare.outputs.release-binary-basename }}/bin/clang.cfg
        git log -n1 --pretty='{"commit":"%H","treehash":"%T","url":"${{ github.repositoryUrl }}"}' > ${{ needs.prepare.outputs.release-binary-basename }}/git-src.json
        XZ_OPT=-9 tar caf \
               ${{ needs.prepare.outputs.release-binary-filename }} \
               ${{ needs.prepare.outputs.release-binary-basename }}
        ls -lh ${{ needs.prepare.outputs.release-binary-filename }}



    - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: Tenjin-LLVM-${{ runner.os }}-${{ runner.arch }}-${{ inputs.release-version }}-nodefaultsysroot-nodefaultcxxstdlib-built_on_${{ inputs.runs-on }}
        # Due to path differences on Windows when running in bash vs running on node,
        # we need to search for files in the current workspace.
        path: |
          ${{ needs.prepare.outputs.release-binary-filename }}
          libcxx/
          dota/
          clickhouse-sysroot/

