name: BuildLLVM

on:
  push:
    branches: [ "test-build-llvm" ]

  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      runs-on:
        description: "Runner to use for the build"
        required: true
        type: choice
        options:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-13 # x86_64
          - macos-14 # arm64

jobs:
  prepare:
    name: Prepare to build binaries
    runs-on: ${{ inputs.runs-on }}
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
      ref: ${{ steps.vars.outputs.ref }}
      #upload: ${{ steps.vars.outputs.upload }}
      target-cmake-flags: ${{ steps.vars.outputs.target-cmake-flags }}
      #build-flang: ${{ steps.vars.outputs.build-flang }}
      #enable-pgo: ${{ steps.vars.outputs.enable-pgo }}
      release-binary-basename: ${{ steps.vars.outputs.release-binary-basename }}
      release-binary-filename: ${{ steps.vars.outputs.release-binary-filename }}

    steps:
    # It's good practice to use setup-python, but this is also required on macos-14
    # due to https://github.com/actions/runner-images/issues/10385
    - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
      with:
        python-version: '3.12'

    - name: Checkout builder repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # for print_os_arch.py

    - name: Inspect cwd
      shell: bash
      run: ls -lh

    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: 'llvm/llvm-project'
        ref: 'llvmorg-${{ inputs.release-version }}'
        path: 'llvmproj'
        clean: false
        fetch-depth: 1

    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r ./llvmproj/llvm/utils/git/requirements.txt
    - name: Inspect cwd again
      shell: bash
      run: ls -lh

    - name: Collect Variables
      id: vars
      shell: bash
      run: |
        trimmed=$(echo ${{ inputs.release-version }} | xargs)
        release_version="$trimmed"
        ref="llvmorg-$release_version"
        upload="false"
        echo "release-version=$release_version">> $GITHUB_OUTPUT
        echo "ref=$ref" >> $GITHUB_OUTPUT
        echo "upload=$upload" >> $GITHUB_OUTPUT
        # Detect necessary CMake flags
        target=$(python3 print_os_arch.py)
        release_binary_basename="LLVM-$release_version-$target"
        echo "release-binary-basename=$release_binary_basename" >> $GITHUB_OUTPUT
        echo "release-binary-filename=$release_binary_basename.tar.xz" >> $GITHUB_OUTPUT
        echo "enable-pgo=false" >> $GITHUB_OUTPUT
        target_cmake_flags="-DLLVM_RELEASE_ENABLE_PGO=OFF"
        # The macOS builds try to cross compile some libraries so we need to
        # add extra CMake args to disable them.
        # See https://github.com/llvm/llvm-project/issues/99767
        if [ "${{ runner.os }}" = "macOS" ]; then
          target_cmake_flags="$target_cmake_flags -DCOMPILER_RT_ENABLE_IOS=OFF"
          if [ "${{ runner.arch }}" = "ARM64" ]; then
            arches=arm64
          else
            arches=x86_64
          fi
          target_cmake_flags="$target_cmake_flags -DDARWIN_osx_ARCHS=$arches -DDARWIN_osx_BUILTIN_ARCHS=$arches"
        fi
        build_flang="false"
        if [ "${{ runner.os }}" = "Windows" ]; then
          # The build times out on Windows, so we need to disable LTO.
          target_cmake_flags="$target_cmake_flags -DLLVM_RELEASE_ENABLE_LTO=OFF"
        fi
        echo "target-cmake-flags=$target_cmake_flags" >> $GITHUB_OUTPUT
        echo "build-flang=$build_flang" >> $GITHUB_OUTPUT
        
  build-llvm-clang:
    name: "Build LLVM and Clang"
    needs: prepare
    runs-on: ${{ inputs.runs-on }}
    steps:

    - name: Install Ninja
      uses: llvm/actions/install-ninja@22e9f909d35b50bd1181709564bfe816eaeaae81 # main

    - name: Checkout builder repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: 'llvm/llvm-project'
        ref: ${{ needs.prepare.outputs.ref }}
        path: 'llvmproj'
        clean: false
        fetch-depth: 1

    - name: Disable llvm-exegesis
      shell: bash
      run: |
        #rm -rf llvmproj/llvm/tools/llvm-exegesis
        #sed -i.bak 's/llvm-exegesis//' llvmproj/llvm/unittests/tools/CMakeLists.txt
        #rm llvmproj/llvm/unittests/tools/llvm-exegesis/CMakeLists.txt
        echo '...eventually...'

    - name: Build Clang
      id: build
      shell: bash
      run: |
        # There were some issues on the ARM64 MacOS runners with trying to build x86 object,
        # so we need to set some extra cmake flags to disable this.
        cmake -G Ninja -S llvmproj/llvm -B llvmproj/_build \
            ${{ needs.prepare.outputs.target-cmake-flags }} \
            -DLLVM_PARALLEL_LINK_JOBS=2 \
            -DCPACK_PACKAGE_FILE_NAME="${{ needs.prepare.outputs.release-binary-basename }}" \
            -DCMAKE_BUILD_TYPE=MinSizeRel \
            -DLLVM_TARGETS_TO_BUILD=host \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF \
            -DLLVM_BUILD_LLVM_DYLIB=ON \
            -DLLVM_LINK_LLVM_DYLIB=ON \
            -DLLVM_ENABLE_ZSTD=OFF \
            -DLLVM_ENABLE_LIBXML2=OFF \
            -DLLVM_ENABLE_CURL=OFF \
            -DLLVM_ENABLE_HTTPLIB=OFF \
            -DLLVM_ENABLE_TERMINFO=OFF \
            -DLLVM_ENABLE_PROJECTS="llvm;clang;lld" \
            -DLLVM_USE_RELATIVE_PATHS_IN_FILES=ON \
            -DCLANG_DEFAULT_LINKER=lld \
            -DCLANG_VENDOR=Tenjin \
            -DCPACK_GENERATOR=TXZ \
            -DCPACK_ARCHIVE_THREADS=0

        ninja -v -C llvmproj/_build
        # There is a race condition on the MacOS builders and this command is here
        # to help debug that when it happens.
        ls -ltr llvmproj/_build

    - name: Build Clang (package)
      shell: bash
      run: |
        ninja -v -C llvmproj/_build package

    - name: Prep Package
      shell: bash
      run: |
        # Copy Release artifact to the workspace so it is easier to upload.
        # This is necessary, because on Windows, the build-prefix path can
        # only be used on bash steps, because it uses the form of /d/files/
        # and other steps expect D:\files.

        mv llvmproj/_build/*.xz .
        ls -lh ${{ needs.prepare.outputs.release-binary-filename }}
        
        # The .a files that feed in to libLLVM and libClang are huge and we don't need them!
        # But CMake & llvm-config will barf if they are missing, so we'll replace them with empty files.
        mkdir dota
        tar xf ${{ needs.prepare.outputs.release-binary-filename }}
        rm     ${{ needs.prepare.outputs.release-binary-filename }}

        # Compute an initial tree hash
        cd ${{ needs.prepare.outputs.release-binary-basename }}
        git init .
        git config user.email "b.tenjin@qt.fyi"
        git config user.name "tenjinbot"
        git add .
        git commit -m .
        intial_treehash=$(git log -n1 --pretty='%T')
        cd ..

        echo "initial treehash: $initial_treehash"
        echo '-----------------'
        ls -lh ${{ needs.prepare.outputs.release-binary-basename }}/*
        echo '-----------------'

        for x in `ls ${{ needs.prepare.outputs.release-binary-basename }}/lib/libLLVM*.a`; do
          mv $x dota/
          touch $x
        done
        for x in `ls ${{ needs.prepare.outputs.release-binary-basename }}/lib/libclang*.a`; do
          mv $x dota/
          touch $x
        done

        rm ${{ needs.prepare.outputs.release-binary-basename }}/bin/llvm-exegesis

        # Compute a final tree hash, without the contents of libLLVM*.a and libclang*.a
        cd ${{ needs.prepare.outputs.release-binary-basename }}
        pwd
        echo '==============='
        ls -al
        echo '==============='

        pwd
        echo 'doing git add .'
        git add .
        echo 'doing git commit -m .'
        git commit -m .
        echo 'doing git log treehash'
        final_treehash=$(git log -n1 --pretty='%T')
        echo "final treehash: $final_treehash"
        echo 'removing .git directory'
        rm -rf .git
        cd ..

        (jq -cn '$ARGS.named' --arg treehash_initial $initial_treehash --arg treehash_final $final_treehash > tarball-treehashes.json) || touch tarball-treehashes.json

        #jq -cn '$ARGS.named' --arg treehash_initial $initial_treehash > tarball-treehashes.json

        pwd
        echo 'computing git-src.json'

        git log -n1 --pretty='{"commit":"%H","treehash":"%T","url":"${{ github.repositoryUrl }}"}' > ${{ needs.prepare.outputs.release-binary-basename }}/git-src.json
        XZ_OPT=-9 tar caf \
               ${{ needs.prepare.outputs.release-binary-filename }} \
               ${{ needs.prepare.outputs.release-binary-basename }}
        ls -lh ${{ needs.prepare.outputs.release-binary-filename }}


    - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: ${{ runner.os }}-${{ runner.arch }}-release-binary
        # Due to path differences on Windows when running in bash vs running on node,
        # we need to search for files in the current workspace.
        path: |
          ${{ needs.prepare.outputs.release-binary-filename }}
          tarball-treehashes.json
          dota



